### ISSUE TITLE
Problem with the coinmarketcap.py file (?)

### ISSUE THREAD

**Issue by 2000jago** [bonovoxly/coinmarketcap-exporter#5]
:~$ sudo docker run --rm -it --entrypoint=/bin/bash -p 127.0.0.1:9101:9101 -v ${PWD}:/opt/coinmarketcap-exporter coinmarketcap-exporter:latest
root@aa4a1d24e51f:/opt/coinmarketcap-exporter# python coinmarketcap.py
2019-10-21 05:02:00,101 - coinmarketcap-exporter - INFO - listening on http://0.0.0.0:9101/metrics
2019-10-21 05:02:00,104 - coinmarketcap-exporter - INFO - collecting...
Traceback (most recent call last):
  File "coinmarketcap.py", line 73, in <module>
    REGISTRY.register(CoinCollector())
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "coinmarketcap.py", line 46, in collect
    response = self.client.tickers(start)
  File "/usr/local/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "coinmarketcap.py", line 34, in tickers
    return json.loads(r.content.decode('UTF-8'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
root@aa4a1d24e51f:/opt/coinmarketcap-exporter#

Cant seem to get beyond this point and don't understand why.  prometheus installed and working.

**Comment by bonovoxly** [comment]
I'm guessing the coinmarketcap api has changed. I've been meaning to clean this up (there's another issue).

Let's see what we can find.

**Comment by 2000jago** [comment]
Should we be holding out for an update or should I just abandon the idea and try to find a different solution to getting some nice coinmarketcap graphs in grafana?

**Comment by bonovoxly** [comment]
I hope to have it resolved in the near future (Just got back from travel)...

**Comment by bonovoxly** [comment]
It appears that it requires an API key now.

https://coinmarketcap.com/api/

Will add this support.

**Comment by 2000jago** [comment]
> It appears that it requires an API key now.

I have signed up for (and received) an API key in anticipation.

**Comment by 2000jago** [comment]
Any chance of an update?

**Comment by bonovoxly** [comment]
Working on it as we speak.

They've changed quite a bit with their api. currently testing and developing.

**Comment by bonovoxly** [comment]
https://github.com/bonovoxly/coinmarketcap-exporter/pull/7

Testing this. You can test using the docker image `bcawthra/coinmarketcap-exporter:api-key`

**Comment by bonovoxly** [comment]
Resolved via https://github.com/bonovoxly/coinmarketcap-exporter/pull/7/
